# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.CharField(max_length=50)),
                ('event_id', models.UUIDField(null=True)),
                ('answered', models.BooleanField(default=False)),
                ('decision', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchedulingTask')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=30)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('location', models.CharField(default=b'X', max_length=50)),
                ('feedback', models.BooleanField(default=False)),
            ],
        ),
    ]
