# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('day', models.IntegerField()),
                ('timeslot', models.IntegerField()),
                ('location', models.CharField(default=b'X', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RankingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=30)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('location', models.CharField(default=b'X', max_length=50)),
                ('feedback', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
